name: test

on:
  push:

  schedule:
    - cron: '0 0 * * *'

jobs:
  test:
    strategy:
      fail-fast: false
    matrix:
      os:
        - macos-12
        - macos-11
    runs-on: ${{ matrix.os }}
  steps:
    - name: TestVm.WasmMemoryLimit 100 times
      run: ./test.sh
